spring:
  application:
    name: cloud-gateway
  cache:
    redis:
      time-to-live: 1000S
    type: simple

  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    redis:
      host: localhost
      port: 6379

